# Generated by Django 2.2.25 on 2022-02-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Img', models.ImageField(upload_to='downloads')),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
