# Generated by Django 2.2.25 on 2022-02-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220214_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Price',
            new_name='Price_Ksh',
        ),
    ]
