# Generated by Django 2.2.25 on 2022-02-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220215_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password1',
            new_name='password2',
        ),
    ]
