# Generated by Django 2.2.25 on 2022-02-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220215_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='kim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
