# Generated by Django 2.2.25 on 2022-02-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220221_0614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kim',
        ),
    ]
