# Generated by Django 2.2.25 on 2022-02-21 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_kim'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
