# Generated by Django 4.0.2 on 2022-02-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220226_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
